name: Validate Filenames

on: [push, pull_request]

jobs:
  check-invalid-filenames:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for Windows-incompatible filenames
        run: |
          echo "🔍 Checking for invalid filenames..."
          
          # List all files in the repository (excluding directories)
          echo "Listing files in repository..."
          files=$(git ls-files)
          echo "Files found in the repository:"
          echo "$files"
          
          # Check for files with Windows-incompatible characters
          invalid_files=$(echo "$files" | grep -P '([<>:"\\|?*])')
          
          # Debugging: Show files with invalid characters
          if [[ -z "$invalid_files" ]]; then
            echo "✅ No invalid filenames found!"
          else
            echo "❌ Error: The following files contain invalid Windows characters:"
            echo "$invalid_files"
            echo "🛑 Please rename these files and push again."
            exit 1
          fi
